### ISSUE TITLE
installing dev-master sql error

### ISSUE THREAD

**Issue by jadwigo** [GawainLynch/bolt-extension-clientlogin#5]
When I install dev-master the database update that wants to create the table drops a whoopsie with the following message

```
An exception occurred while executing '
CREATE TABLE bolt_client_sessions (
  id INT AUTO_INCREMENT NOT NULL, 
  userid INT NOT NULL, 
  session VARCHAR(64) NOT NULL, 
  token LONGTEXT DEFAULT NULL, 
  lastseen DATETIME NOT NULL, 
  INDEX IDX_B644867F132696E (userid), 
  INDEX IDX_B6448675F37A13B (token), 
  PRIMARY KEY(id)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB':
SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'token' used in key specification without a key length
```

My guess is that the index on https://github.com/GawainLynch/bolt-extension-clientlogin/blob/master/src/Database.php#L513 need a length parameter

**Comment by GawainLynch** [comment]
Fixed in f7a3111110e5e0b29724d5bf97ceaa891402e20c 

Apparently it also kinda helps if you index the *correct* column :see_no_evil:
